### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by dbw9580** [lirenjie95/MCS-51Experiment#1]
3.15:
>MOV @R0, 20H; 寄存器间接寻址， 将 20H 单元中的内容送入寄存器 R0， R0=30H

问的是源操作数的寻址方式
另，这题一共7条指令，答案里漏写了一条

3.19(5):
>MOV DPTR, #2000H MOVX A, @DPTR MOV R0, A

要求放在20H内存单元里，不是R0

**Comment by lirenjie95** [comment]
博文好棒(´･ω･`)
话说我应该上周写好之后就传上来
