### ISSUE TITLE
Comments on Homework3.pdf

### ISSUE THREAD

**Issue by dbw9580** [lirenjie95/MCS-51Experiment#2]
3.31：

>程序执行后 A=80H,SP=42H,(41H)=50H,(42H)=80H,PC=8050H.

SP在RET前是42H，RET将42H,41H两个单元弹出到PC中了，所以SP应该减小到40H

3.29：

>MOV @R0, SP; 把 SP 指向地址里面的值送入 R0 指向的地址，即(40H)=14H

SP是直接寻址，指的就是SP中的内容，即81H单元
所以是把SP的值送入@R0

**Comment by lirenjie95** [comment]
第二个看不太懂😥

**Comment by dbw9580** [comment]
sp就是sp本身，不是其中的内容作为内存的指针
2016年3月24日 17:28于 Renjie Li <notifications@github.com>写道：第二个看不太懂😥

**Comment by lirenjie95** [comment]
已经修正
